### ISSUE TITLE
- [ ] needs updated test expectations

### ISSUE THREAD

**Issue by Shuhaib07** [unisat-wallet/dev-support#60]
- [ ] needs updated test expectations
- [ ] depends on PR #15258
- [ ] depends on PR #15259
- [ ] depends on PR #15260
- [ ] depends on PR #15242

_Originally posted by @clonker in https://github.com/ethereum/solidity/pull/15281_
